version: "3.9"
services:
  dbtest:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: rando
    image: "postgres:alpine"
    volumes:
      - db-data:/var/lib/postgres/data

    ports:
      - "5432:5432"
  web:
    build: .
volumes:
  db-data:

