version: "3.9"
services:
  dbtest:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    image: "postgres:alpine"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: backend
    build: .
    depends_on:
      - dbtest
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@dbtest:5432/example
    volumes:
      - .:/projecttt
    ports:
      - "5000:5000"
    restart: "always"
  frontend:
    container_name: react-app
    build:
      context: ./web/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - reactvol:/usr/src/app
    depends_on:
      - web
volumes:
  db-data:
  reactvol:

